version: '3.1'
services:
    db:
        image: postgres:10.8
        #image: postgres:16.1-alpine
        ports:
            - '${DATABASE_PORT}:5432'
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: '${DATABASE_NAME}'
            POSTGRES_USER: '${DATABASE_USERNAME}'
            POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
    phppgadmin:
        restart: always
        image: dockage/phppgadmin:latest
        ports:
            - '${DATABASE_WEB_PORT}:80'
        environment:
            PHP_PG_ADMIN_SERVER_DEFAULT_DB: '${DATABASE_NAME}'
            PHP_PG_ADMIN_SERVER_HOST: 'db'
            PHP_PG_ADMIN_SERVER_PORT: '${DATABASE_PORT}'
